###  Shedule start
POST http://localhost:9010/start
Content-Type: application/json

{
  "ip": "http://5.23.48.96:9000",
  "period": 3
}


### Shedule stop
GET http://localhost:9010/stop/

### Shedules shows
GET http://localhost:9010/jobs/